name: Generate Changelog

on:
  push:
    branches: [develop]

jobs:
  generate-changelog:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get last successful commit
        id: last-successful-commit
        uses: ./.github/actions/last-successful-commit-action
        with:
          github_token: ${{ github.token }}
          workflow_id: generate-changelog.yml
          branch: develop
          debug: true

      - name: Generate release notes
        id: generate-release-notes
        run: |
          if [[ -z "${{ steps.last-successful-commit.outputs.commit_hash }}" ]]; then
            echo "Error: Unable to generate release notes. Last successful build commit not available."
            exit 1
          fi
          echo "Generating release notes..."

          # Generate release notes from commits
          RELEASE_NOTES=$(git log --oneline --no-decorate ${{ steps.last-successful-commit.outputs.commit_hash }}..${{ github.sha }} | cut -d ' ' -f2-)
      
          # Convert multiline string to single line string. See https://trstringer.com/github-actions-multiline-strings/#option-1---string-substitution
          RELEASE_NOTES="${RELEASE_NOTES//'%'/'%25'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\n'/'%0A' - }"
          RELEASE_NOTES=" - ${RELEASE_NOTES//$'\r'/'%0D'}"

          # Save output
          echo "release_notes=$RELEASE_NOTES" >> "$GITHUB_OUTPUT"

      - name: Output release notes
        run: |
          echo "Generated release notes:"
          echo "${{ steps.generate-release-notes.outputs.release_notes}}"
