name: Generate Changelog

on:
  push:
    branches: [develop]

jobs:
  generate-changelog:
    permissions:
      actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get last successful commit
        id: last-successful-commit
        uses: ./.github/actions/last-successful-commit-action
        with:
          github_token: ${{ github.token }}
          workflow_id: generate-changelog.yml
          branch: develop
          debug: true

      - name: Generate release notes
        id: generate-release-notes
        run: |
          if [[ -z "${{ steps.last-successful-commit.outputs.commit_hash }}" ]]; then
            echo "Error: Unable to generate release notes. Last successful build commit not available."
            exit 1
          fi
          echo "Generating release notes..."

          # Generate release notes from commits
          RELEASE_NOTES=$(git log --oneline --no-decorate ${{ steps.last-successful-commit.outputs.commit_hash }}..${{ github.sha }} | cut -d ' ' -f2- | sed 's/^/- /')

          echo "Generated release notes:"
          echo "$RELEASE_NOTES"

          # Output multiline string. See https://github.com/orgs/community/discussions/26288#discussioncomment-3876281
          echo "Saving output..."
          delimiter="$(openssl rand -hex 8)"
          echo "release_notes<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo "$RELEASE_NOTES" >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

      - name: Display release notes
        run: |
          echo "Generated release notes:"
          echo "${{ steps.generate-release-notes.outputs.release_notes}}"
