name: Generate Changelog

on:
  push:
    branches: [develop]

jobs:
  generate-changelog:
    permissions:
      actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get last successful commit
        id: last-successful-commit
        uses: ./.github/actions/last-successful-commit-action
        with:
          github-token: ${{ github.token }}
          workflow-id: generate-changelog.yml
          branch: develop
          debug: true

      - name: Generate release notes
        id: generate-release-notes
        uses: ./.github/actions/generate-release-notes-action
        with:
          begin-sha: ${{ steps.last-successful-commit.outputs.commit-hash }}

      - name: Display release notes
        run: |
          echo "Release notes:"
          # Use single quotes to prevent special characters from being interpreted
          echo '${{ steps.generate-release-notes.outputs.release-notes }}'
