name: Generate Changelog

on:
  push:
    branches: [generate-changelog_develop]
  workflow_dispatch:

jobs:
  generate-changelog:
    permissions:
      actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get last successful commit
        id: last-successful-commit
        uses: tylermilner/last-successful-commit-hash-action@75c8b699e495079741cfde5a20522c3658b723c5
        with:
          github-token: ${{ github.token }}
          workflow-id: generate-changelog.yml
          branch: generate-changelog_develop
          debug: true

      - name: Generate release notes
        id: generate-release-notes
        uses: ./.github/actions/generate-release-notes-action
        with:
          begin-sha: ${{ steps.last-successful-commit.outputs.commit-hash }}
          release-notes-file: release-notes.txt

      - name: Display release notes
        run: |
          echo "Release notes:"
          cat release-notes.txt
