name: Test

on: [push, workflow_dispatch]

jobs:
    test:
        runs-on:
            - self-hosted
            - macos-12
        steps:
            - uses: actions/checkout@v3

            - name: Set up ruby env
              uses: ruby/setup-ruby@v1
              with:
                bundler-cache: true # Automatically runs `bundle install` and caches the result

            - name: Run tests
              run: |
                bundle exec fastlane ios test
