name: Test

on: [push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Mint
        run: |
          git clone https://github.com/yonaskolb/Mint.git
          cd Mint
          make install
      
      - name: Run Swiftlint
        run: |
          mint bootstrap
          export LINUX_SOURCEKIT_LIB_PATH=/usr/lib/swift/lib
          mint run swiftlint

  test:
    needs: lint
    runs-on:
      - self-hosted
      - macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # Automatically runs `bundle install` and caches the result

      - name: Run tests
        run: |
          bundle exec fastlane ios test
